### ISSUE TITLE
Total records written should reflect the number of rows in the source file 

### ISSUE THREAD

**Issue by trosesandler** [worldflora/tpl#6]
Currently the  total records written is the sum of all records processed at each step of the import which is not all that useful to a administrator.  An administrator needs to verify if all the rows in the source file were ingested properly so there needs to be some sort of count for that on the resource page.

**Comment by mdoering** [comment]
@trosesandler isn't this rather an eMonocot harvesting issue not a plant list archive one?

**Comment by trosesandler** [comment]
yes sorry it wasn't clear to me if we wanted to also record issues with eMonocot here so I will just maintain a separate list for those and close this issue

**Comment by mdoering** [comment]
@trosesandler you can use this repo to create issues we have with the eMonocot software:
https://github.com/worldflora/eMonocot
